# infrastructure/argocd/apps/infrastructure/security/cert-manager-config/templates/cluster-issuer.yaml

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: wynn.cn666@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - selector:
        dnsZones:
          - "core-platform.click"
      dns01:
        route53:
          region: us-east-1
          secretAccessKeySecretRef:
            name: ""