# k8s/base/services/audit/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: audit-server
  labels:
    app: audit-server
spec:
  selector:
    app: audit-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50068
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
