# infrastructure/argocd/apps/infrastructure/security/cert-manager/values.yaml
installCRDs: true

serviceAccount:
  create: true
  name: cert-manager

cainjector:
  enabled: true
  serviceAccount:
    create: true
    name: cert-manager-cainjector

webhook:
  enabled: true
  serviceAccount:
    create: true
    name: cert-manager-webhook