# infrastructure/argocd/apps/observability/monitoring/monitoring.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-monitoring-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.0.0
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              external-dns.alpha.kubernetes.io/hostname: grafana.core-platform.click
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
              alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.global.certificateArn }}"
              alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
            hosts:
              - grafana.core-platform.click
        prometheus:
          prometheusSpec:
            retention: 10d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "gp3"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
