# infrastructure/argocd/templates/load-tests.yaml

{{- range .Values.loadTests }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-{{ .name }}-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <ton-repo-git>
    targetRevision: HEAD
    path: {{ .path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: load-tests
  syncPolicy: {} # Manuel par défaut
---
{{- end }}