# infrastructure/argocd/apps/catalog/profile-service/templates/shared/ingress.yaml

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName | default "management-group" | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    {{- end }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host | quote }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.commandServer.name }}
                port:
                  number: {{ .Values.commandServer.port }}
{{- end }}
