# infrastructure/argocd-bis/apps/catalog/profile-service/templates/shared/karpenter.yaml

{{- if .Values.karpenter.enabled }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.serviceName }}-{{ .Values.envName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: {{ .Values.karpenter.capacityType | default "[\"on-demand\"]" }}
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: {{ .Values.karpenter.instanceTypes | default "[\"t3.medium\"]" }}
      nodeClassRef:
        name: default # Ou une classe spécifique définie dans ton infra
{{- end }}