# k8s/base/services/social-graph/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: social-graph-server
  labels:
    app: social-graph-server
spec:
  selector:
    app: social-graph-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
