# infrastructure/argocd/apps/infrastructure/observability/monitoring/templates/grafana-ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn:
      { { .Values.certificateArn | quote } }
    external-dns.alpha.kubernetes.io/hostname: "grafana.core-platform.click"
spec:
  ingressClassName: alb
  rules:
    - host: "grafana.core-platform.click"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  number: 80
