# k8s/base/services/engagement/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: engagement-server
  labels:
    app: engagement-server
spec:
  selector:
    app: engagement-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50058
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
