# infrastructure/argocd/apps/deployments/dev/domain-appset.yaml

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-workloads
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/arnaudmaillet/core-platform
        revision: feat/profile/stress-test-clean
        files:
          - path: "infrastructure/argocd/apps/deployments/dev/**/*.yaml"
          - path: "!infrastructure/argocd/apps/deployments/dev/domain-appset.yaml"
  template:
    metadata:
      name: 'dev-{{ .path.basename }}-{{ .path.filenameWithoutExt }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/arnaudmaillet/core-platform
          targetRevision: feat/profile/stress-test-clean
          path: 'infrastructure/argocd/apps/catalog/{{ .path.basename }}-service'
          helm:
            valueFiles:
              - '$values/infrastructure/argocd/bootstrap/global-params.json'
              - '$values/{{ .path.path }}'
        - repoURL: https://github.com/arnaudmaillet/core-platform
          targetRevision: feat/profile/stress-test-clean
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev-{{ .path.basename }}'
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true]