# infrastructure/argocd/apps/deployments/dev/domain-appset.yaml

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-workloads
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/arnaudmaillet/core-platform
              revision: develop
              files:
                - path: "infrastructure/argocd/apps/deployments/dev/profile/*.yaml"
              pathParamPrefix: app
          - git:
              repoURL: https://github.com/arnaudmaillet/core-platform
              revision: develop
              files:
                - path: "infrastructure/argocd/bootstrap/global-params.json"
  template:
    metadata:
      name: 'dev-{{ .appPath.basenameDir }}-{{ .appPath.basename }}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/arnaudmaillet/core-platform
          targetRevision: develop
          path: 'infrastructure/argocd/apps/catalog/{{ .appPath.basenameDir }}-service'
          helm:
            values: |
              global:
                certificateArn: "{{ .certificateArn }}"
              componentType: "{{ .appPath.basename }}"
            valueFiles:
              - '$values/{{ .appPath.path }}'
        - repoURL: https://github.com/arnaudmaillet/core-platform
          targetRevision: develop
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev-{{ .appPath.basenameDir }}'
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions:
          - CreateNamespace=true