# infrastructure/argocd/apps/deployments/dev/profile-app.values.yaml

global:
  certificateArn: "arn:aws:acm:us-east-1:724772065879:certificate/dff68fbe-02a5-4c9c-9a6b-41c71de34522"
  
serviceName: "profile"
componentType: "app"
envName: "dev"

app:
  commandServer:
    replicas: 2
    image:
      repository: "724772065879.dkr.ecr.us-east-1.amazonaws.com/core-platform-profile-command-server"
      tag: "v1.2.3"
    resources:
      requests: { cpu: "10m", memory: "100Mi" }
      limits: { cpu: "1000m", memory: "512Mi" }

  # Configuration du lien vers les storage.yaml
  endpoints:
    postgres: "profile-postgres-rw:5432"
    scylla: "profile-scylla"
    redis: "profile-redis:6379"

ingress:
  enabled: true
  host: "api.dev.core-platform.click"
  groupName: "management-group"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 80