# infrastructure/argocd/apps/deployments/dev/profile-storage.values.yaml

serviceName: "profile"
componentType: "storage"
envName: "dev"

persistence:
  postgresql:
    name: "profile-postgres"
    storage: "10Gi"
    version: "16-3.5" # PostGIS

  nosql:
    name: "profile-scylla"
    image: "scylladb/scylla:5.4"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    args: ["--smp", "1", "--memory", "512M", "--overprovisioned", "1"]

  cache:
    name: "profile-redis"
    version: "7-alpine"
