# infrastructure/argocd/apps/infrastructure/platform/aws-lb-controller/values.yaml

clusterName: ""
clusterEndpoint: ""
env: ""

aws-load-balancer-controller:
  clusterName: ""
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: ""
