# k8s/base/services/account/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: account-server
  labels:
    app: account-server
spec:
  selector:
    app: account-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50059
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
