# k8s/overlays/dev/load-tests/command-server/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scaling-test-run.yaml # On pointe vers le fichier de ressource K6
  - seed-job.yaml

secretGenerator:
  - name: dev-profile-db-app
    type: Opaque
    literals:
      - password=${DB_PASSWORD}