# k8s/overlays/dev/load-tests/command-server/scaling-test-run.yaml

apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: profile-command-scaling-test
  namespace: load-tests
spec:
  # L'opérateur va créer 4 Pods "runners". 
  # Chaque runner suit le scenario du script (ex: 200 req/s), 
  # soit 800 req/s au total sur ton API.
  parallelism: 4
  
  script:
    localFile: /test/script.js
      
  runner:
    image: 724772065879.dkr.ecr.us-east-1.amazonaws.com/core-platform-k6-tests:latest
    env:
      - name: K6_SCRIPT
        value: "/test/script.js"
      - name: K6_STATSD_ENABLE_TAGS
        value: "true"

    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    
    nodeSelector:
      intent: load-tests 
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "load-testing"
        effect: "NoSchedule"