---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-profile-db-app
  namespace: load-tests
spec:
  encryptedData:
    password: AgCWz5XJqDCK5H0CRUo8Gia8HJjt96SnSwXPdazAYGy9lKqu47xH7F0XOYrCG2MSMO5JU6YhtCpMeM8CAigu7UBTJV4jWW6M3hrvCl7TjLYaqrZciKtNY30uOJGMLn+SmWxcNSw1y1PSPWPzPXyL7Y+3LoEWoYKYxEGNYar0NhIXxSqRTfCSqBpfqLVHRzmGg/begfT4Np3ue/fB4MO3qHmIjdv98UOT0/yJ5MxJDmK0Ccu1zzVh89xH3lUNElGEkx0I+e5h+lt5R9szKntIoFdh3M4DNqh497OzWGwiMSe+8hBYsJ8O3G9HugAeaJCoPXMk7Y5qTiOI9m/nvafT1rVSKfVCsb4FIs1QGuRax51LeSjrFRVg9P91VV66C9x+QPPYz7HORbjQunUEFPYY7t+N7IymZTNKoQVBKuddi7IBPeVJDO2Q6QWqis2ONw3lBWQ6d+cRnBjn8yz7kISCTpqD4367i1yzWBCXjNmQEmcfyeagBryUAFKhS/jwLOOK2P4HuJyBEZSkpF5/zEiyKsazp5SS/Hk8rL/kNJG3uHSWKBWwY4b/MGSkelAGXwOXWszqw29SWFUj+VQrve1GoE93Gm5CxR23WiFZchmw/42+t1ZqdlJFedlfsbzDN9VLI7dxdaNDZ4BUNKtdgCen/X+nhsrBGL6tlwxeX1oyQy0BswBaeJRj3dRpLxOfY+Rcthnh87ihCOVwKw==
  template:
    metadata:
      name: dev-profile-db-app
      namespace: load-tests
