---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-profile-db-app
  namespace: load-tests
spec:
  encryptedData:
    password: AgAdV/AOEBTEnMqMEu2ZKq+FoDuFlELjKQ2jYdwSogeErYplSz/TUWeAA1pr0Cuk0ko8wLfW9cYt1A+FJny7mivejZXjeHHWx/Asz60HxRSR+rr+xSSoGLOY2j6fPKEYIRaXY4306JBWchBtVIaBEsWpEi2RqnZt0ZkVMFVJvrsWbWn5Ne8c23NKNXo3g972GYlXxMcbw4UPJsBLIYa0eOd2WTp8SjWF6twtrfZ+iL3S7JKUKeyZLrYEJiYyaI+Sv4l1UF0gsAu5kvJSPT/AAH9tLM/4dHhN6WaX3GQB8fgoKna2Sea3O03+UWpklR4mH1Q1RVfBSZIv/VMCg9jFXgekH5sDUVZoBtlpBq4TgjS1JmVpn4M53+mmffEVUiIhizz6pgF3Yc1W5EH6N73Uv8vEq4GTq8WGSmNi6J7ml/rEIE3FJQ12cKT922zR52vY6FndbvC0xWsQz3KXgXGM5kwA+J0+PrzbmQREKISP3TVS/6SUTiTMLJabzXqURrsVE7V00/DMvD3FelrjgAFfCbCcXl62z3AUA9hWTVyLqqcSlc3hHrPd0zEfJm4uSQSg2/YfT0glsuB8s/l/G6Q00ip0TS/h4th193LvPoP+BFC0ePCyh6pT93YLEYt0R4vHVJ61bQbC+MFwbA049Wd9qxCjW0wGGoWPVgyV3V030vUJwXIt1rxLj0PLMJir/xhuvGXJb9ORV4byBP8jPx4StvG5ZSUktY7/Ljzwobjp2HRfvTPN3y7sjHsPz1vvT1YEnmwWeBd0hhasfC/VgkTi+lvm
  template:
    metadata:
      name: dev-profile-db-app
      namespace: load-tests
