---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-profile-db-app
  namespace: load-tests
spec:
  encryptedData:
    password: AgCHgtZmUITT3iWzkeqaGki49a+UKb0vx0nYZWCFcM9LrUoK1Jid3ovU2kXOsaHL976mFTAPwLmrEdeHfK6wriyglJDukydd/FNH5XPfkALBY/chUykh5e/bbrpsAqt48ax6ikIR1tMmjfLQtoBP67tKXQgvZc11SyqZ5trdNCrSnanmu0Kueao1LA45dnwextjF6HQHAahSjsJjVhnAiuZmVtMrqDYAnsKzzV4eWwbdG3WkuIW3JiOUyROSnW3jc54FtcgdToKmI6d1bvYt92Z4QO6zOBxn7iHQjhgKG+wOdgbUqT80e7oHaMqG/vLH2PMI0YZO/oclgjCwQHFR+U3BJ8J+jxe01MaQyhzCgelVebLm3ue1E7RK0jbVG8UMF86btrQgR80ubLJtSjoBAauEvY47eoFSpQI5piNtS2SR80BwDDoaIbUIbHoosDGWLmhnbh0YwSL+h4HGkJVPjpeZzrner4PmCBfEwHnP4ntPfY9cskHH8dp8ue91JwCS7K9KhuPIER19h6tDnuQeR7LLbNtMyHz++kRd/k4vX4MsT4UTcxeHO0/TJhrgXqbHPpr4KRzgrICkvKuSwCEyShHs/etlnnFalzDde6NhzlDzpeCWZYXBfsrDP6etrfLuPwD9jbqUAqeOOLixrtx4ZHDqO3VNyNACPDlKGNen/ZHMqSFCkrBgl6YK6+RGAGjjp9k=
  template:
    metadata:
      name: dev-profile-db-app
      namespace: load-tests
