# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "core-platform-terraform-state-dev"
    encrypt      = true
    key          = "live/dev/us-east-1/kubernetes/external-secrets-config/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
