# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
resource "kubernetes_manifest" "cluster_secret_store" {
  manifest = {
    # CHANGEMENT ICI : v1 au lieu de v1beta1
    apiVersion = "external-secrets.io/v1"
    kind       = "ClusterSecretStore"
    metadata = {
      name = "aws-secretsmanager"
    }
    spec = {
      provider = {
        aws = {
          service = "SecretsManager"
          region  = "us-east-1"
          auth = {
            jwt = {
              serviceAccountRef = {
                name      = "external-secrets"
                namespace = "external-secrets"
              }
            }
          }
        }
      }
    }
  }
}
