# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  # Default tags appliqués à TOUTES les ressources du projet
  default_tags {
    tags = {
      Project     = "core-platform"
      Environment = "dev"
      ManagedBy   = "Terraform/Terragrunt"
    }
  }
}
