# k8s/base/services/post/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: post-server
  labels:
    app: post-server
spec:
  selector:
    app: post-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50056
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
