# infrastructure/argocd/apps/infrastructure/observability/monitoring/values.yaml

kube-prometheus-stack:
  grafana:
    enabled: true
    ingress:
      enabled: false
  prometheus:
    prometheusSpec:
      retention: 10d
