# infrastructure/argocd/apps/infrastructure/platform/karpenter-config/templates/nodeclass.yaml

apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  # On utilise le rôle créé par Terraform pour les nœuds
  role: "{{ .Values.global.clusterName }}-karpenter-node-role"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Values.global.clusterName }}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Values.global.clusterName }}"
  tags:
    Intent: apps
    ManagedBy: Karpenter
    Environment: "{{ .Values.global.env }}"