# infrastructure/argocd/apps/deployments/dev/values/profile-service.yaml

serviceName: "profile-service"
envName: "dev"

# --- CONFIGURATION DES MICROSERVICES ---
commandServer:
  enabled: true
  name: "dev-profile-command-server"
  port: 50051
  configMapName: "dev-profile-api-config"
  dbSecretName: "dev-profile-db-app"
  dbUrl: "postgres://app:$(_DB_PASSWORD)@dev-profile-db-rw:5432/profile"
  
  image:
    repository: "724772065879.dkr.ecr.us-east-1.amazonaws.com/core-platform-profile-command-server"
    tag: "latest"
    
  resources:
    requests:
      cpu: "10m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

  initContainers:
    scylla:
      enabled: true
      image: "scylladb/scylla:latest"
      command: |
        until cqlsh dev-profile-nosql -e "CREATE KEYSPACE IF NOT EXISTS profile_service WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};" ; do
          echo "Waiting for ScyllaDB to be ready..."
          sleep 5
        done

  service:
    type: ClusterIP
    annotations: {}

queryServer:
  enabled: false

# --- CONFIGURATION RÉSEAU (INGRESS) ---
ingress:
  enabled: true
  host: "api.dev.core-platform.click"
  groupName: "management-group"

# --- CONFIGURATION SCALING (HPA) ---
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPU: 80

# --- CONFIGURATION DU PLACEMENT (Standard K8s) ---
nodeSelector:
  karpenter.sh/capacity-type: "spot"

# --- CONFIGURATION BDDs ---
databases:
  postgres:
    enabled: true
    name: "dev-profile-db"
    instances: 1
    image: "ghcr.io/cloudnative-pg/postgis:16-3.5"
    dbName: "profile"
    owner: "app"
    storageSize: "10Gi"

  redis:
    enabled: true
    name: "dev-profile-redis"
    image: "redis:7-alpine"

  scylla:
    enabled: true
    name: "dev-profile-nosql"
    image: "scylladb/scylla:5.4"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    args: [ "--smp", "1", "--memory", "512M", "--overprovisioned", "1" ]
