# infrastructure/argocd/values.yaml

global:
  env: "dev"
  certificateArn: ""
  clusterName: ""
  clusterEndpoint: ""
  externalDnsRoleArn: ""
  karpenterRoleArn: ""


loadTests:
  - name: profile-command
    path: k8s/overlays/dev/load-tests/command-server