# infrastructure/argocd/apps/infrastructure/platform/karpenter/values.yaml

karpenter:
  settings:
    clusterName: ""
    clusterEndpoint: ""
    interruptionQueue: "core-platform-dev"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ""
