# k8s/base/services/moderation/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: moderation-server
  labels:
    app: moderation-server
spec:
  selector:
    app: moderation-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50061
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
