# infrastructure/argocd/apps/workload/load-tests/load-tests.yaml

{{- range .Values.loadTests }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-{{ .name }}-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arnaudmaillet/core-platform
    targetRevision: HEAD
    path: {{ .path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: load-tests
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
{{- end }}