# k8s/base/services/notification/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-server
  labels:
    app: notification-server
spec:
  selector:
    app: notification-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50055
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
