# k8s/base/services/comment/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: comment-server
  labels:
    app: comment-server
spec:
  selector:
    app: comment-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50057
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
