# infrastructure/argocd/apps/catalog/profile-service/templates/command/deployment.yaml

{{- if eq .Values.componentType "app" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.commandServer.name | default (printf "%s-command-server" .Values.serviceName) }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.app.commandServer.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.commandServer.name | default (printf "%s-command-server" .Values.serviceName) }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.commandServer.name | default (printf "%s-command-server" .Values.serviceName) }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      # --- INIT CONTAINER (Attente & Setup Scylla) ---
      initContainers:
        - name: init-scylla-keyspace
          image: "scylladb/scylla:latest"
          command: 
            - "/bin/bash"
            - "-c"
            - |
              until cqlsh {{ .Values.app.endpoints.scylla }} -e "CREATE KEYSPACE IF NOT EXISTS {{ .Values.app.endpoints.keyspace | default "profile_service" }} WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};" ; do
                echo "Waiting for ScyllaDB ({{ .Values.app.endpoints.scylla }}) to be ready..."
                sleep 5
              done

      containers:
        - name: server
          image: "{{ .Values.app.commandServer.image.repository }}:{{ .Values.app.commandServer.image.tag }}"
          resources:
            {{- toYaml .Values.app.commandServer.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.commandServer.configMapName | default (printf "%s-config" .Values.serviceName) }}
          env:
            # --- POSTGRES ---
            - name: _DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "profile-postgres-app" 
                  key: password
            - name: PROFILE_DB_URL
              value: {{ printf "postgres://app:$(_DB_PASSWORD)@%s/profile" .Values.app.endpoints.postgres | quote }}

            # --- SCYLLA ---
            - name: PROFILE_SCYLLA_NODES
              value: {{ .Values.app.endpoints.scylla | quote }}
            - name: PROFILE_SCYLLA_KEYSPACE
              value: {{ .Values.app.endpoints.keyspace | default "profile_service" | quote }}

            # --- REDIS ---
            - name: PROFILE_REDIS_URL
              value: {{ printf "redis://%s" .Values.app.endpoints.redis | quote }}

          ports:
            - containerPort: {{ .Values.app.commandServer.port | default 50051 }}
{{- end }}