# infrastructure/argocd/apps/catalog/profile-service/templates/command/deployment.yaml

{{- if .Values.commandServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.commandServer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.commandServer.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.commandServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.commandServer.name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.commandServer.initContainers.scylla.enabled }}
      initContainers:
        - name: init-scylla-keyspace
          image: {{ .Values.commandServer.initContainers.scylla.image | quote }}
          command: ["/bin/bash", "-c", {{ .Values.commandServer.initContainers.scylla.command | quote }}]
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.commandServer.image.repository }}:{{ .Values.commandServer.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.commandServer.configMapName }}
          env:
            # --- POSTGRES ---
            - name: _DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-app" .Values.databases.postgres.name }}
                  key: password
            - name: PROFILE_DB_URL
              value: {{ printf "postgres://app:$(_DB_PASSWORD)@%s-rw:5432/%s" .Values.databases.postgres.name .Values.databases.postgres.dbName | quote }}

            # --- SCYLLA ---
            - name: PROFILE_SCYLLA_NODES
              value: {{ .Values.databases.scylla.name | quote }}
            - name: PROFILE_SCYLLA_KEYSPACE
              value: {{ .Values.databases.scylla.keyspace | quote }}

            # --- REDIS ---
            - name: PROFILE_REDIS_URL
              value: {{ printf "redis://%s:6379" .Values.databases.redis.name | quote }}

          ports:
            - containerPort: {{ .Values.commandServer.port }}
{{- end }}