# infrastructure/argocd/apps/catalog/profile-service/templates/command/deployment.yaml

{{- if .Values.commandServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.commandServer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.commandServer.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.commandServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.commandServer.name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.commandServer.initContainers.scylla.enabled }}
      initContainers:
        - name: init-scylla-keyspace
          image: {{ .Values.commandServer.initContainers.scylla.image | quote }}
          command: ["/bin/bash", "-c", {{ .Values.commandServer.initContainers.scylla.command | quote }}]
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.commandServer.image.repository }}:{{ .Values.commandServer.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.commandServer.configMapName }}
          env:
            # 1. On récupère d'abord le mot de passe du secret CNPG
            - name: _DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  # CNPG crée toujours un secret nom-du-cluster-app
                  name: {{ .Values.commandServer.dbSecretName | default (printf "%s-app" .Values.databases.postgres.name) }}
                  key: password
            
            # 2. On injecte l'URL en utilisant la variable récupérée juste au-dessus
            - name: PROFILE_DB_URL
              # Note : On utilise $(VAR) pour l'interpolation K8s
              value: "postgres://app:$(_DB_PASSWORD)@{{ .Values.databases.postgres.name }}-rw:5432/{{ .Values.databases.postgres.dbName }}"
          ports:
            - containerPort: {{ .Values.commandServer.port }}
{{- end }}