# infrastructure/argocd/apps/catalog/profile-service/templates/command/service.yaml

{{- if eq .Values.componentType "app" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.commandServer.name | default (printf "%s-command-server" .Values.serviceName) }}
  annotations:
    {{- if and .Values.app.commandServer.service .Values.app.commandServer.service.annotations }}
    {{- toYaml .Values.app.commandServer.service.annotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.app.commandServer.name | default (printf "%s-command-server" .Values.serviceName) }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.app.commandServer.port | default 50051 }}
      targetPort: {{ .Values.app.commandServer.port | default 50051 }}
      appProtocol: grpc
  type: {{ if .Values.app.commandServer.service }}{{ .Values.app.commandServer.service.type | default "ClusterIP" }}{{ else }}ClusterIP{{ end }}
{{- end }}