# infrastructure/argocd/apps/operators/k6-operator/Chart.yaml

apiVersion: v2
name: k6-operator-wrapper
version: 1.0.0
dependencies:
  - name: k6-operator
    version: "3.6.0"
    repository: https://grafana.github.io/helm-charts