# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "core-platform-terraform-state-dev"
    encrypt      = true
    key          = "./terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
