# k8s/base/services/chat/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chat-server
  labels:
    app: chat-server
spec:
  selector:
    app: chat-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
