# k8s/base/services/counter/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: counter-server
  labels:
    app: counter-server
spec:
  selector:
    app: counter-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50064
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
