# infrastructure/argocd/apps/infrastructure/security/external-dns/values.yaml

external-dns:
  provider: aws
  domainFilters:
    - "core-platform.click"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ""
  policy: upsert-only
  registry: txt
  txtOwnerId: "core-platform-dev"
  sources:
    - ingress
    - service