# k8s/overlays/dev/karpenter-config.yaml

# 1. NODEPOOL POUR LES WORKERS
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: worker # Kustomize ajoutera 'dev-' devant
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default # Doit matcher le nom de l'EC2NodeClass plus bas
      requirements:
        - key: "role"
          operator: In
          values: ["worker"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m"]
  limits:
    cpu: "50"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
# 2. NODEPOOL POUR LA DATABASE
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: storage
spec:
  template:
    metadata:
      labels:
        role: storage
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
        - key: dedicated
          value: database
          effect: NoSchedule
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["r"]
  limits:
    cpu: "50"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "core-platform-dev-node-role"
  amiSelectorTerms:
    - alias: al2@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "core-platform-dev"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "core-platform-dev"