# k8s/base/services/geo-discovery/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: geo-discovery-server
  labels:
    app: geo-discovery-server
spec:
  selector:
    app: geo-discovery-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50054
      targetPort: grpc
      appProtocol: grpc
  type: ClusterIP
